source 'http://rubygems.org'

gem 'rails', '3.1.1'

gem 'jquery-rails'

gem 'sqlite3'

gem 'attached', :path => ".."

group :assets do
  gem 'sass-rails',   '~> 3.1.0'
  gem 'coffee-rails', '~> 3.1.0'
  gem 'uglifier'
end

group :test do
  gem 'mocha'
  gem 'minitest'
  gem 'simplecov', require: false
  gem 'turn', require: false
end