require File.expand_path('../config/application', __FILE__)
require 'rake'

if defined? Rake::DSL
  module ::Attached
    class Application
      include Rake::DSL
    end
  end
end

if defined? Rake::FileUtilsExt
  module ::RakeFileUtils
    extend Rake::FileUtilsExt
  end
end

Attached::Application.load_tasks
